name: Build and Release .NET App

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          path: bin/Release/net6.0
          name: app

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Get the release number
        run: echo "RELEASE_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Create a release
        uses: actions/create-release@v1
        with:
          tag_name: $RELEASE_VERSION
          release_name: $RELEASE_VERSION
          body: |
            This is the release notes for version $RELEASE_VERSION.
      - name: Upload build artifacts
        uses: actions/upload-release-asset@v1
        with:
          asset_path: bin/Release/net6.0
          asset_name: app
          asset_content_type: application/zip
